"""Ajout des colonnes difficulty et category avec valeurs par défaut

Revision ID: de93d82f7762
Revises: 
Create Date: 2025-07-04 00:08:54.780690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de93d82f7762'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        op.add_column('question', sa.Column('difficulty', sa.String(length=20), nullable=False, server_default='moyen'))
        op.add_column('question', sa.Column('category', sa.String(length=20), nullable=False, server_default='qi'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
